name: Android Release Build and Publish

on:
  push:
    tags:
      - 'v*' # 仅在推送 v 开头的 tag 时触发

# 授予创建 Release 和上传资源的权限
permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 代码
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 设置 JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      # 3. 授予 Gradle Wrapper 执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. 配置签名文件
      - name: Decode Keystore
        # 确保这里的路径是以 /release.keystore 结尾！
        run: echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > ${{ github.workspace }}/release.keystore
        env:
          SIGNING_KEYSTORE_BASE64: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}

      - name: Create signing.properties
        run: |
          echo "keystore.password=${{ secrets.KEYSTORE_PASSWORD }}" > ${{ github.workspace }}/signing.properties
          echo "key.alias=${{ secrets.KEY_ALIAS }}" >> ${{ github.workspace }}/signing.properties
          echo "key.password=${{ secrets.KEY_PASSWORD }}" >> ${{ github.workspace }}/signing.properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # 5. 执行 Gradle 构建 (Release 版本)
      - name: Build Release APK
        run: ./gradlew assembleRelease
        # 如果构建 AAB，则使用: ./gradlew bundleRelease

      # 6. 创建 GitHub Release 并上传 APK
      #    使用 softprops/action-gh-release action
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}

          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/release/ECJTU-PDA-${{ github.ref_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}